### ISSUE TITLE
FoD: Load only releases with valid scan results

### ISSUE THREAD

**Issue by rsenden** [fortify/FortifySyncFoDToSSC#7]
At the moment, the sample configuration file shows the following configuration to only take FoD releases with either static or dynamic scan results into account for the linkReleases task:

```yaml
    linkReleases:
      fod:
        filters:
          release:
            filterExpressions:
            - staticScanDate!=null || dynamicScanDate!=null
```

We should discuss with the FoD team whether there is any possibility to perform this filtering at the FoD side (i.e. have a filter parameter that tells FoD to return only releases that have specific scan results), instead of first loading all releases and then filtering on the client side.

In addition, the filter should be improved to include only releases for which these scan results are actually downloadable (i.e. less than x years old)
